# -*- coding: utf-8 -*-
"""Clips_Filtering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMGGjPc0EdLRX-jCPGufQBKLBEU9F6VO
"""

import pandas as pd
import moviepy.editor as mp
from moviepy.editor import VideoFileClip, concatenate_videoclips
import os
import numpy as np

def is_bowlerrunup_exists(df): 
    y=df['PlayerCount'].to_numpy()
    for i in range(5):
      if y[i]>=3:
        return 1
    return 0

def diff(x):
  unique_elements, counts_elements = np.unique(x, return_counts=True)
  if(unique_elements.size<=1):
    return 0
  unique_elements.sort()
  return abs (unique_elements[0]-unique_elements[unique_elements.size-1])

def remove_subclip(clip,low,high):
  filename='drive/My Drive/Processedvideo/highlights_without_replay/'+clip+'.mp4'
  video=VideoFileClip(filename)
  clip1=video.subclip(0,low-1)
  duration=int(video.duration)
  print(duration)
  clip2=video.subclip(high+1,duration-1)
  final_clip = concatenate_videoclips([clip1,clip2])
  final_clip.write_videofile(filename)

def subclips_removal_time(clip,array):
  i=1
  ones_count=0
  size=array.size
  while i<size :
    if array[i]==1:
      ones_count=ones_count+1
    else:
      if ones_count!=0 and ones_count>=3:
        high=i-1
        low=i-ones_count
        print(low,high)
        remove_subclip(clip,low,high)
        return
      ones_count=0
    i=i+1

def clips_filter():
    df=pd.read_csv('drive/My Drive/Processedvideo/data.csv', index_col=0, parse_dates=True)
    folders=os.listdir('drive/My Drive/Processedvideo/keyframe')
    clips_count=len(folders)
    clips=np.zeros(clips_count+1)
    i=1
    while i<=clips_count:
      df1 = df[df['ClipNumber']=='clip'+str(i)] 
      score=df1['Score'].to_numpy()
      wickets=df1['Wickets'].to_numpy()
      crowd=df1['CrowdView'].to_numpy()
      ground=df1['GroundView'].to_numpy()
      #subclips_removal_time(crowd)
      #subclips_removal_time(ground)
      if diff(score)>=4 :
        clips[i]=1
      if diff(wickets)>=1 :
        clips[i]=1
      if(is_bowlerrunup_exists(df1)==0):
        clips[i]=0
      i=i+1
    return clips

if __name__ == '__main__':
  clips=clips_filter()
  print(clips)
  i=1
  index=[]
  while i<clips.size:
    if clips[i]==1:
      index.append(i)
    i=i+1
  i=1
  print(index)
  final_clip=VideoFileClip('drive/My Drive/Processedvideo/highlights_without_replay/clip'+str(index[0])+'.mp4')
  while i<len(index):
    filename='drive/My Drive/Processedvideo/highlights_without_replay/clip'+str(index[i])+'.mp4'
    clip1=VideoFileClip(filename)
    final_clip = concatenate_videoclips([final_clip,clip1])
    i=i+1
  final_clip.write_videofile("drive/My Drive/Processedvideo/Highlights_final1.mp4")

final_clip.write_videofile("drive/My Drive/Processedvideo/Highlights_final1.mp4")