# -*- coding: utf-8 -*-
"""crowd_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-WLUUmIn1Ljhxlj3GUDqaqpaQ6z8I8P
"""

import cv2
from google.colab.patches import cv2_imshow
def is_crowd_view(img_path):
  image = cv2.imread(img_path,cv2.IMREAD_UNCHANGED)
  gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  edges = cv2.Canny(gray,100,200)
  edges=cv2.resize(edges,(200,200))
  cv2_imshow(edges)
  hist = cv2.calcHist([edges], [0] , None, [256], [0, 256])
  ratio=hist[255]/hist[0]
  if ratio>0.08:
    return 1
  else:
    return 0