# -*- coding: utf-8 -*-
"""ground_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Spv5ZAbdWQzdVGQTKHk4NYWW53CHywP
"""

import cv2
from google.colab.patches import cv2_imshow
from matplotlib import pyplot as plt
def is_ground_view(filename) :
  img = cv2.imread(filename)
  HSV_img = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
  hist = cv2.calcHist([HSV_img], [0] , None, [256], [0, 256])
  #plt.plot(hist, color = 'g')
  #plt.xlim([0, 256])
  #plt.show()
  hsv=cv2.resize(HSV_img,(200,200))
  cv2_imshow(hsv)
  i=0
  sum=0
  total=0
  while i<=255:
    total=total+hist[i]
    if i>=30 and i<=60:
      sum=sum+hist[i]
    i=i+1
  if(sum/total>0.7):
    return 1
  else:
    return 0