# -*- coding: utf-8 -*-
"""Save_data_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACXAn1b-8IjgcFVQUTh3fNvX9mekYBKG
"""

import os
import glob
import pandas as pd
import pathlib
from detection_from_scoreboard import get_wickets_and_score
from runup_detection import get_players_count
from crowd_detection import is_crowd_view
from ground_detection import is_ground_view

if __name__ == '__main__':
  dir=os.listdir('drive/My Drive/Processedvideo/keyframe')
  df=pd.DataFrame(columns=['ClipNumber','FrameNumber','Score','Wickets','PlayerCount','GroundView','CrowdView'])
  for foldername in dir:
    foldername='drive/My Drive/Processedvideo/keyframe/'+foldername+'/*.jpg'
    print(foldername)
    for filename in glob.glob(foldername):
      print(filename)
      path = pathlib.PurePath(filename)
      clipname=path.parent.name
      framename=path.name
      framename=framename.replace('.jpg','')
      a=get_wickets_and_score(filename)
      b=get_players_count(filename)
      c=is_ground_view(filename)
      d=is_crowd_view(filename)

      new_row = {'ClipNumber':clipname, 'FrameNumber':framename, 'Score':str(a[0]), 'Wickets':str(a[1]),'PlayerCount':b,'GroundView':c,'CrowdView':d}
      print(new_row)
      df = df.append(new_row, ignore_index=True)
   compression_opts = dict(method='zip',archive_name='data.csv')  
   df.to_csv('data.zip', index=False,compression=compression_opts)