# -*- coding: utf-8 -*-
"""videos_with_no_replay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b1UlRvRMtJVBIu4KRJ9XvK6Tk3gDH2vk
"""

from replay import replay_predictions
from video_with_no_replay import load_clip_without_replay
import cv2
import glob
import os
import time
from google.colab.patches import cv2_imshow
import moviepy.editor as mp
from moviepy.editor import VideoFileClip, concatenate_videoclips

def predictions_with_time(filename,time):
  vidcap=cv2.VideoCapture(filename)
  vidcap.set(cv2.CAP_PROP_POS_MSEC,time)
  success,image=vidcap.read()
  if success:
    cv2.imwrite('abc.jpg',image)
    prediction=replay_predictions('abc.jpg')
    cv2.waitKey()
    return prediction[0]

def get_split_index(predictions,duration):
  i=1
  time=duration/1000
  while i<len(predictions):
    if predictions[i]==1 and predictions[i-1]==1 :
      time=i-1
      break
    i=i+1
  return time

def get_split_time(filename):
  video = VideoFileClip(filename)
  duration=int(video.duration)
  duration=duration*1000
  i=0
  predictions=[]
  while i<=duration:
    predictions.append(predictions_with_time(filename,i))
    i=i+1000
  print(predictions)
  return get_split_index(predictions,duration)

def load_clip_without_replay(filename,number):
  time=get_split_time(filename)
  print("time:",time)
  video=VideoFileClip(filename)
  clip=video.subclip(0,time)
  target_filename="drive/My Drive/Processedvideo/highlights_without_replay/clip"+str(number)+".mp4"
  clip.write_videofile(target_filename)

if __name__ == '__main__':
    count=1
    for filename in glob.glob("drive/My Drive/Processedvideo/highlights/*.mp4"):
      filename='drive/My Drive/Processedvideo/highlights/clip'+str(count)+'.mp4'
      load_clip_without_replay(filename,count)
      count=count+1

